#!/bin/sh

echo "Running Gradle task: autoTranslate"
./gradlew autoTranslate

if [ $? -ne 0 ]; then
    echo "Gradle task 'autoTranslate' failed. Please fix the issues."
    exit 1
fi

echo "Gradle task 'autoTranslate' completed successfully."
