name: Add Missing Translations

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'src/main/res/**'       # corresponds to autoTranslate.translateStringsXml.resDirectory
      - 'fastlane/metadata/**'  # corresponds to autoTranslate.translateFastlane.metadataDirectory

permissions:
  contents: write

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Run Gradle autoTranslate
        env:
          AUTO_TRANSLATE_API_KEY: ${{ secrets.AUTO_TRANSLATE_API_KEY }}
        run: ./gradlew autoTranslate

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Add missing translations
